### ISSUE TITLE
Wrong data in popup

### ISSUE THREAD

**Issue by clach04** [peterhil/spellbook#31]
Installed 0.3.7, first time trying spellbook. Folder search is awesome :)

Often (but I can not reproduce 100% of the time) the wrong URL is present on screen in the add bookmark widget (e.g. about:blank instead of the address in the address bar), sometimes the wrong title is present too (and wrong URL).

The wrong title is less frequent.

To "fix" it I end up closing tab, reopening and copy.pasting URL which works on about the 3rd try.

I do have a lot of tabs in case that helps

**Comment by peterhil** [comment]
I know there has sometimes been problems on updating the correct information, and have solved some problems in 0.4.0 and 0.4.1 releases.

Now on 0.4.0 the main problem is that sometimes the bookmark parent paths are wrong, which has been fixed in 0.4.1, so please update to that version.

**Comment by peterhil** [comment]
This bug was still present and is finally fixed by:
* #36 Only get current tab info once the popup is opened: Fixed with [commit #99902f0](https://github.com/peterhil/spellbook/commit/99902f0)

Similar bugs are hopefully prevented in the future by:
* #40 Optimise asynchronous requests
* #41 Use Svelte stores for state management
